server:
  servlet:
    context-path: /

spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      routes:
        - id: logs-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/log/**, /logs-service/v3/api-docs
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,INTERNAL_SERVER_ERROR
            methods: GET,POST,PUT
        - name: CircuitBreaker
          args:
            name: globalCircuitBreaker
            fallbackUri: forward:/fallback

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: api-gateway
        url: /v3/api-docs
        display-name: api-gateway
      - name: logs-service
        url: /logs-service/v3/api-docs
        display-name: logs-service

logging:
  level:
    org.springframework.cloud.gateway: DEBUG