server:
  port: 8085
  servlet:
    context-path: /
  ssl:
    key-store: classpath:apiGateway.p12  # or use file:/... if external
    key-store-password: ApiG@teway@2025
    key-store-type: PKCS12
    key-alias: apigateway

spring:
  profiles:
    active: @spring.profiles.active@

  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      routes:
        - id: logs-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/log/**, /v3/api-docs/logs-service
        - id: logs-service
          uri: http://localhost:8083
          predicates:
            - Path=/iot/**, /v3/api-docs/iot-service
        - id: websocket-route
          uri: ws://localhost:8083
          predicates:
            - Path=/iot/ws/**
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,INTERNAL_SERVER_ERROR
            methods: GET,POST,PUT
        - name: CircuitBreaker
          args:
            name: globalCircuitBreaker
            fallbackUri: forward:/fallback
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://159.65.131.28:8443/realms/RAC
          jwk-set-uri: https://159.65.131.28:8443/realms/RAC/protocol/openid-connect/certs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: api-gateway
        url: /v3/api-docs
        display-name: api-gateway
      - name: logs-service
        url: /v3/api-docs/logs-service
        display-name: logs-service
      - name: iot-service
        url: /v3/api-docs/iot-service
        display-name: iot-service


logging:
  level:
    root: INFO

    # Gateway core routing and filters
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.filter: DEBUG

    # Netty & WebFlux details
    reactor.netty.http.client: DEBUG
    reactor.netty: INFO

    # Spring Security
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.oauth2.server.resource.web.access.server: DEBUG

    # Retry & CircuitBreaker
    org.springframework.cloud.gateway.filter.factory.RetryGatewayFilterFactory: DEBUG
    org.springframework.cloud.gateway.filter.factory.CircuitBreakerGatewayFilterFactory: DEBUG
    io.github.resilience4j: DEBUG

    # Swagger / Springdoc
    org.springdoc: INFO

  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

file:
  path:
    cert: D:\Work and School\Project\IoT\keycloak.crt

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show:
        details: "always"
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0