spring.profiles.active=@spring.profiles.active@
spring.application.name=logs-service
server.port=8082
spring.data.mongodb.uri=mongodb://iot:pwd%402025@159.65.131.28:27017/
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=logs
spring.data.mongodb.username=iot
spring.data.mongodb.password=pwd@2025
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


mqtt.url=tcp://159.65.131.28:1883
mqtt.username=iot_log
mqtt.password=iot@log2025


server.servlet.context-path=/
openapi.service.title=logs-service
openapi.service.version=3.0.0
openapi.service.url=https://localhost:8085
openapi.service.local-url=http://localhost:8082
springdoc.api-docs.path=/logs-service/v3/api-docs
springdoc.swagger-ui.path=/logs-service/swagger-ui.html

spring.cloud.compatibility-verifier.enabled=false

logging.level.org.springframework=info
logging.level.com.authz=debug
logging.level.root=info
logging.file.name=/opt/tomcat/logs/agritechiot/agritechiot.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - [%-5level] %-32.32logger{32} - TRACE: %-36X{TRACE_ID}]: %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - [%-5level] %-32.32logger{32} - TRACE: %-36X{TRACE_ID}]: %msg%n
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=debug